### ISSUE TITLE
Gemini cookbook

### ISSUE THREAD

**Issue by RazHadas** [dmatrix/genai-cookbook#107]
Hi,
Great job on this repository, I really like it.
Why don't you have any Gemini codes? My company works quite a lot with Gemini. We may contribute code for function calling in Gemini and maybe more.

**Comment by dmatrix** [comment]
I plan to include Gemini soon. But I welcome contributions too. Have to try Gemmini free version.

**Comment by dmatrix** [comment]
Added PR for [gemini](https://github.com/dmatrix/genai-cookbook/pull/110).
More will be added.

**Comment by dmatrix** [comment]
Added basic some client creation functionality for Gemini flash 1.5. Will added some more examples.
